# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 925493516b7d94593b89158119b550589aec032059dec6b65daa9595d321786aea75e84fcb0e6e28f7948a35b9f2e3f1d816fb22b7112e9488ccfc2bf5dcb18c

test:
  secret_key_base: ef418317ac54e68a8a89cd72dbdf4d33d8ce46d995a844e8e94a8cec05e8d999b87d95b9d478bf4192a5e6115cc300042284dbb813934affc15ad447cfe4f87a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
